import numpy as np

df_dict = {
    'School Code': {'dtype': object, 'name': 'school_code'},
    'School Name': {'dtype': object, 'name': 'school_name'},
    'School Type': {'dtype': object, 'name': 'school_type'},
    'Town': {'dtype': object, 'name': 'town'},
    # 'PK_Enrollment': {'dtype': np.float64, 'name': 'pk_enroll'},
    # '1_Enrollment': {'dtype': np.float64, 'name': '1_enroll'},
    # '2_Enrollment': {'dtype': np.float64, 'name': '2_enroll'},
    # '3_Enrollment': {'dtype': np.float64, 'name': '3_enroll'},
    # '4_Enrollment': {'dtype': np.float64, 'name': '4_enroll'},
    # '5_Enrollment': {'dtype': np.float64, 'name': '5_enroll'},
    # '6_Enrollment': {'dtype': np.float64, 'name': '6_enroll'},
    # '7_Enrollment': {'dtype': np.float64, 'name': '7_enroll'},
    # '8_Enrollment': {'dtype': np.float64, 'name': '8_enroll'},
    # '9_Enrollment': {'dtype': np.float64, 'name': '9_enroll'},
    # '10_Enrollment': {'dtype': np.float64, 'name': '10_enroll'},
    # '11_Enrollment': {'dtype': np.float64, 'name': '11_enroll'},
    # '12_Enrollment': {'dtype': np.float64, 'name': '12_enroll'},
    # 'SP_Enrollment': {'dtype': np.float64, 'name': 'sp_enroll'},
    'TOTAL_Enrollment': {'dtype': np.float64, 'name': 'total_enroll'},
    '% First Language Not English': {'dtype': np.float64, 'name': 'first_language_not_english_p'},
    '% English Language Learner': {'dtype': np.float64, 'name': 'english_language_learner_p'},
    '% Students With Disabilities': {'dtype': np.float64, 'name': 'students_with_disabilities_p'},
    '% High Needs': {'dtype': np.float64, 'name': 'high_needs_p'},
    '% Economically Disadvantaged': {'dtype': np.float64, 'name': 'economically_disadvantaged_p'},
    '% African American': {'dtype': np.float64, 'name': 'african_american_p'},
    '% Asian': {'dtype': np.float64, 'name': 'asian_p'},
    '% Hispanic': {'dtype': np.float64, 'name': 'hispanic_p'},
    '% White': {'dtype': np.float64, 'name': 'white_p'},
    '% Native American': {'dtype': np.float64, 'name': 'native_american_p'},
    '% Native Hawaiian, Pacific Islander': {'dtype': np.float64, 'name': 'hawaiian_p'},
    '% Multi-Race, Non-Hispanic': {'dtype': np.float64, 'name': 'multi_race_p'},
    '% Males': {'dtype': np.float64, 'name': 'males_p'},
    '% Females': {'dtype': np.float64, 'name': 'females_p'},
    'Total # of Classes': {'dtype': np.float64, 'name': 'total_classes'},
    'Average Class Size': {'dtype': np.float64, 'name': 'avg_class_size'},
    'Number of Students': {'dtype': np.float64, 'name': 'num_students'},
    'Average Salary': {'dtype': np.float64, 'name': 'avg_salary'},
    'Total Expenditures': {'dtype': np.float64, 'name': 'total_expend'},
    'Average Expenditures per Pupil': {'dtype': np.float64, 'name': 'avg_expend_per_pupil'},
    'Accountability and Assistance Level': {'dtype': object, 'name': 'accountability_level'},
    'Progress and Performance Index (PPI) - All Students': {'dtype': np.float64, 'name': 'ppi'},
    # 'District_Progress and Performance Index (PPI) - All Students': {'dtype': np.float64, 'name': 'district_ppi'},
}
